(()=>{'use strict';
const CONFIG={siteUrl:'{{VERIFIED_SITE_URL}}',address:'{{VERIFIED_ADDRESS}}',phone:'{{VERIFIED_PHONE}}',email:'{{VERIFIED_EMAIL}}',nextOpening:'{{VERIFIED_NEXT_OPENING}}',formEndpoint:'{{VERIFIED_FORM_ENDPOINT}}',tournaments:[{id:'{{VERIFIED_TOURNAMENT_ID}}',name:'{{VERIFIED_TOURNAMENT_NAME}}',date:'{{VERIFIED_TOURNAMENT_DATE}}',registrationTime:'{{VERIFIED_REGISTRATION_TIME}}',startTime:'{{VERIFIED_START_TIME}}',format:'{{VERIFIED_FORMAT}}',status:'{{VERIFIED_STATUS}}',buyIn:'{{VERIFIED_BUY_IN}}'}],broadcasts:[{status:'{{VERIFIED_BROADCAST_STATUS}}',tournament:'{{VERIFIED_TOURNAMENT_NAME}}',date:'{{VERIFIED_TOURNAMENT_DATE}}',time:'{{VERIFIED_START_TIME}}'}],results:[{date:'{{VERIFIED_RESULT_DATE}}',tournament:'{{VERIFIED_TOURNAMENT_NAME}}',winner:'{{VERIFIED_WINNER}}',resultInfo:'{{VERIFIED_PRIZE_INFO}}'}],structure:[{level:'{{VERIFIED_LEVEL}}',blinds:'{{VERIFIED_BLINDS}}',duration:'{{VERIFIED_LEVEL_DURATION}}'}]};
const STORAGE_KEY='loewen-play-pokerroom-germany-privacy-v2';
const unresolved=v=>!v||/\{\{VERIFIED_[A-Z0-9_]+\}\}/.test(String(v));
const safeGet=()=>{try{return localStorage.getItem(STORAGE_KEY)}catch(e){return null}};const safeSet=v=>{try{localStorage.setItem(STORAGE_KEY,v)}catch(e){}};
const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const hide=el=>{if(!el)return;el.hidden=true;el.classList.add('is-hidden');el.setAttribute('aria-hidden','true')};const show=el=>{if(!el)return;el.hidden=false;el.classList.remove('is-hidden');el.setAttribute('aria-hidden','false')};
const escapeHTML=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const header=q('[data-header]');addEventListener('scroll',()=>header?.classList.toggle('is-scrolled',scrollY>30),{passive:true});
const menu=q('#mobile-menu'),backdrop=q('.menu-backdrop'),toggle=q('.menu-toggle'),closeBtn=q('.menu-close');
function openMenu(){show(menu);show(backdrop);document.body.classList.add('menu-open');toggle?.setAttribute('aria-expanded','true');closeBtn?.focus()}function closeMenu(){hide(menu);hide(backdrop);document.body.classList.remove('menu-open');toggle?.setAttribute('aria-expanded','false')}
toggle?.addEventListener('click',openMenu);closeBtn?.addEventListener('click',closeMenu);backdrop?.addEventListener('click',closeMenu);qa('#mobile-menu a').forEach(a=>a.addEventListener('click',closeMenu));
const banner=q('[data-cookie-banner]'),prefs=q('[data-preferences-modal]'),analytics=q('[data-analytics-choice]');if(safeGet())hide(banner);else show(banner);function choose(value){hide(banner);hide(prefs);safeSet(value)}q('[data-cookie-accept]')?.addEventListener('click',()=>choose('all'));q('[data-cookie-deny]')?.addEventListener('click',()=>choose('necessary'));function openPrefs(){show(prefs);if(analytics)analytics.checked=safeGet()==='all';q('[data-preferences-close]')?.focus()}q('[data-cookie-manage]')?.addEventListener('click',openPrefs);qa('[data-cookie-open]').forEach(b=>b.addEventListener('click',openPrefs));q('[data-preferences-close]')?.addEventListener('click',()=>hide(prefs));q('[data-preferences-save]')?.addEventListener('click',()=>choose(analytics?.checked?'all':'necessary'));
qa('[data-field]').forEach(el=>{const v=CONFIG[el.dataset.field];if(unresolved(v)){el.hidden=true}else{el.textContent=v;el.hidden=false}});qa('.requires-verified').forEach(el=>{const visible=qa('[data-field]',el).some(x=>!x.hidden);if(!visible)hide(el)});
const validRows=(name,keys)=>CONFIG[name].filter(row=>keys.every(k=>!unresolved(row[k])));const tournaments=validRows('tournaments',['id','name','date','startTime','format','status']);const broadcasts=validRows('broadcasts',['status','tournament','date','time']);const results=validRows('results',['date','tournament','winner','resultInfo']);const structure=validRows('structure',['level','blinds','duration']);
const fmtDate=value=>{const d=new Date(value+'T12:00:00');if(Number.isNaN(d.valueOf()))return value;return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Europe/Berlin'}).format(d).replaceAll('/','-')};
const card=t=>`<article class="event-card" data-format="${escapeHTML(t.format.toLowerCase())}" data-status="${escapeHTML(t.status.toLowerCase())}" data-date="${escapeHTML(t.date)}"><div><p class="eyebrow">${escapeHTML(t.status)}</p><h3>${escapeHTML(t.name)}</h3><p>${fmtDate(t.date)} · ${escapeHTML(t.startTime)} · ${escapeHTML(t.format)}</p></div><a class="button button-outline" href="tournament-detail.html?id=${encodeURIComponent(t.id)}">Turnier ansehen</a></article>`;
if(tournaments.length){show(q('[data-tournament-section]'));const home=q('[data-home-tournaments]');if(home)home.innerHTML=tournaments.slice(0,3).map(card).join('');const mini=q('[data-mini-schedule]');if(mini)mini.innerHTML=tournaments.slice(0,3).map(card).join('')}
const list=q('[data-tournament-list]'),cal=q('[data-calendar-view]'),filters=q('[data-tournament-filters]');function renderList(){if(!list)return;const f=q('[name=format]',filters)?.value||'all',s=q('[name=status]',filters)?.value||'all',d=q('[name=date]',filters)?.value||'';const rows=tournaments.filter(t=>(f==='all'||t.format.toLowerCase()===f)&&(s==='all'||t.status.toLowerCase()===s)&&(!d||t.date>=d));list.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty-state">Es wurden noch keine vom Betreiber bestätigten Turniere veröffentlicht.</div>';if(cal)cal.innerHTML=rows.length?`<div class="calendar-grid">${rows.map(t=>`<article><strong>${fmtDate(t.date)}</strong><span>${escapeHTML(t.name)}</span><small>${escapeHTML(t.startTime)}</small></article>`).join('')}</div>`:'<div class="empty-state">Es wurden noch keine vom Betreiber bestätigten Turniere veröffentlicht.</div>'}filters?.addEventListener('input',renderList);q('[data-reset-filters]')?.addEventListener('click',()=>{filters.reset();renderList()});renderList();qa('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{qa('[data-view]').forEach(b=>{b.classList.toggle('is-active',b===btn);b.setAttribute('aria-pressed',String(b===btn))});if(list)list.hidden=btn.dataset.view!=='list';if(cal)cal.hidden=btn.dataset.view!=='calendar'}));
const sList=q('[data-schedule-list]'),sCal=q('[data-schedule-calendar]');function renderSchedule(){if(!sList)return;const query=(q('[data-schedule-search]')?.value||'').toLowerCase(),f=q('[data-schedule-format]')?.value||'all',s=q('[data-schedule-status]')?.value||'all';const rows=tournaments.filter(t=>(!query||(t.name+' '+t.format).toLowerCase().includes(query))&&(f==='all'||t.format.toLowerCase()===f)&&(s==='all'||t.status.toLowerCase()===s));sList.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty-state">Es wurden noch keine vom Betreiber bestätigten Turniere veröffentlicht.</div>';if(sCal)sCal.innerHTML=rows.length?`<div class="calendar-grid">${rows.map(t=>`<article><strong>${fmtDate(t.date)}</strong><span>${escapeHTML(t.name)}</span></article>`).join('')}</div>`:'<div class="empty-state">Es wurden noch keine vom Betreiber bestätigten Turniere veröffentlicht.</div>'}qa('[data-schedule-search],[data-schedule-format],[data-schedule-status]').forEach(el=>el.addEventListener('input',renderSchedule));q('[data-schedule-reset]')?.addEventListener('click',()=>{q('[data-schedule-search]').value='';q('[data-schedule-format]').value='all';q('[data-schedule-status]').value='all';renderSchedule()});renderSchedule();qa('[data-schedule-mode]').forEach(btn=>btn.addEventListener('click',()=>{qa('[data-schedule-mode]').forEach(b=>b.setAttribute('aria-selected',String(b===btn)));if(sList)sList.hidden=btn.dataset.scheduleMode!=='list';if(sCal)sCal.hidden=btn.dataset.scheduleMode!=='calendar'}));
const selected=tournaments[0];if(selected){const map={tournamentStatus:selected.status,tournamentName:selected.name,tournamentDate:fmtDate(selected.date),registrationTime:selected.registrationTime,startTime:selected.startTime,tournamentFormat:selected.format,buyIn:selected.buyIn,address:CONFIG.address};qa('.event-detail [data-field]').forEach(el=>{const v=map[el.dataset.field];if(!unresolved(v)){el.textContent=v;el.hidden=false}})}
const structureEl=q('[data-tournament-structure]');if(structureEl&&structure.length)structureEl.innerHTML=`<table><thead><tr><th>Level</th><th>Blinds</th><th>Dauer</th></tr></thead><tbody>${structure.map(r=>`<tr><td>${escapeHTML(r.level)}</td><td>${escapeHTML(r.blinds)}</td><td>${escapeHTML(r.duration)}</td></tr>`).join('')}</tbody></table>`;qa('[data-tournament-select]').forEach(sel=>tournaments.forEach(t=>sel.insertAdjacentHTML('beforeend',`<option value="${escapeHTML(t.id)}">${escapeHTML(t.name)} · ${fmtDate(t.date)}</option>`)));
const current=broadcasts.find(x=>x.status.toLowerCase()==='live')||broadcasts[0];qa('[data-live-status]').forEach(el=>el.textContent=current?current.status:'Demnächst');const bl=q('[data-broadcast-list]');if(bl&&broadcasts.length)bl.innerHTML=broadcasts.map(b=>`<article class="event-card"><div><p class="eyebrow">${escapeHTML(b.status)}</p><h3>${escapeHTML(b.tournament)}</h3><p>${fmtDate(b.date)} · ${escapeHTML(b.time)}</p></div></article>`).join('');const rl=q('[data-results-list]');if(rl&&results.length)rl.innerHTML=results.map(r=>`<article class="result-card"><p class="eyebrow">${fmtDate(r.date)}</p><h3>${escapeHTML(r.tournament)}</h3><p><strong>${escapeHTML(r.winner)}</strong></p><p>${escapeHTML(r.resultInfo)}</p></article>`).join('');
qa('[data-accordion] article').forEach(article=>{const b=q('button',article),panel=q('div',article);b?.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));panel.hidden=open;q('b',b).textContent=open?'+':'−'})});
const gallery=q('[data-gallery-modal]');qa('[data-gallery-src]').forEach(btn=>btn.addEventListener('click',()=>{q('img',gallery).src=btn.dataset.gallerySrc;show(gallery)}));q('[data-gallery-close]')?.addEventListener('click',()=>hide(gallery));gallery?.addEventListener('click',e=>{if(e.target===gallery)hide(gallery)});
qa('form[data-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const msg=q('.form-message',form);qa('.invalid',form).forEach(x=>x.classList.remove('invalid'));let first=null;qa('[required]',form).forEach(el=>{const bad=el.type==='checkbox'?!el.checked:!el.value.trim()||(el.type==='email'&&!/^\S+@\S+\.\S+$/.test(el.value));if(bad){el.classList.add('invalid');first=first||el}});if(first){msg.textContent='Bitte prüfen Sie die markierten Felder.';msg.className='form-message error';first.focus();return}msg.textContent='Die Eingaben wurden geprüft, aber noch nicht versendet. Verbinden Sie zuerst einen sicheren und verifizierten Kontaktkanal.';msg.className='form-message error'}));
qa('.section>.shell,.section-heading,.info-card').forEach(el=>el.classList.add('reveal'));if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.08});qa('.reveal').forEach(el=>io.observe(el))}else qa('.reveal').forEach(el=>el.classList.add('in-view'));
q('.back-to-top')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));qa('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();hide(prefs);hide(gallery)}});
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const bad=[];while(walker.nextNode())if(/\{\{VERIFIED_/.test(walker.currentNode.nodeValue))bad.push(walker.currentNode);bad.forEach(n=>hide(n.parentElement));
})();